#!/bin/bash

# This will only work if you have just one card.
# This is a hack, not actually production code, d'uh
BOSE=$(pacmd list-cards | grep bluez_card | sed 's/.*<bluez_card.\(.*\)>/\1/')

case "$1" in
    audio)
	SINK=a2dp_sink
	;;
    mic)
	SINK=handsfree_head_unit
	;;
esac

pactl set-card-profile bluez_card.${BOSE} ${SINK}
pacmd set-default-sink bluez_sink.${BOSE}.${SINK}
